### PR TITLE
Cosmic text persistent buffer

### PR DESCRIPTION
**Pull request by bytemunch**
Apologies for the double PR, just learning proper use of git remotes and interacting across forks :S

Previous text:

Hi :) Hope this is the right place to send code changes!

I got persistent buffers working, the method feels a bit messy and ad-hoc and I'm sure there's a better way of doing this.

Next steps are passing buffer into create_text_measure and then removing the create_buffer method, then shoring up the buffer creation when no cache hit.

I'd appreciate it you could do a quick review and let me know if I'm doing anything majorly odd or if this is a good path to carry on with?

### CODE REVIEW

**Comment by TotalKrill** [comment]
Looking at this, Im generally wary about the commands.entity(ent).insert(Buffer) behaviour, it can lead to strange bugs when people are like adding/removing an entity really quick. 

At least I have memories of issues like this happening, dont know if I imagined it or not though. 

But at least add the buffer to the different textbundles, so they exist when creating those bundles.

**Comment by TotalKrill** [comment]
And, looking at this, maybe we could aim at removing the create_buffer function and instead use only the update_buffer function. 

This approach feels like it works better with the ECS mindset, especially if there are other crates who needs access to this information. 

This needs a rebase as well though, because I have updated the create_buffer function, to better reflect updates in cosmic-text

**Comment by bytemunch** [comment]
Yeah I wasn't sure about inserting the buffer to the entity, does feel like it could be unstable, will try some quick create/removes after rebasing and tidying up

**Comment by bytemunch** [comment]
@TotalKrill I had an absolute nightmare trying to get a proper rebase done, took the easier option of just redoing the changes manually :)

Have removed the component adding bits, and found where the `TextBundle` is defined and added a buffer to that too.

Unsure if changing `TextBundle` and `Text2dBundle` is enough to always expect a `CosmicBuffer` on the entity? I've kept the option-checking flow for now.

**Comment by TotalKrill** [comment]
Hmm, yeah I am unsure too, I think this is the right path to go though, but the requriement of a CosmicBuffer on each entity that wants texts is something we will need to understand. 

I _feel_ that adding it to the bundles should be enough. The query doesnt need the Option then as well. 

Maybe we should aim at doing this change after the cosmic-text PR has been merged? 

Edit: After thinking some more, I think we should get this in ASAP, this is much more ECS, if there  are issues, getting this in early will help a lot. I have some time right now, so I can help some unless you happen to be online

**Pull request merged**
